/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeacherTestRouteImport } from './routes/teacher/test'
import { Route as TeacherReportsRouteImport } from './routes/teacher/reports'
import { Route as TeacherProgressRouteImport } from './routes/teacher/progress'
import { Route as TeacherExamRouteImport } from './routes/teacher/exam'
import { Route as TeacherBankRouteImport } from './routes/teacher/bank'
import { Route as TeacherAssignRouteImport } from './routes/teacher/assign'
import { Route as TeacherAiRouteImport } from './routes/teacher/ai'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentPracticeRouteImport } from './routes/student/practice'
import { Route as StudentCompetencyRouteImport } from './routes/student/competency'
import { Route as StudentBattleRouteImport } from './routes/student/battle'
import { Route as StudentAssignmentsRouteImport } from './routes/student/assignments'
import { Route as StudentAiRouteImport } from './routes/student/ai'
import { Route as StudentAchievementsRouteImport } from './routes/student/achievements'
import { Route as SachToan4RouteImport } from './routes/sach/toan-4'
import { Route as SachKhoaHoc4RouteImport } from './routes/sach/khoa-hoc-4'
import { Route as SachBookIdRouteImport } from './routes/sach/$bookId'
import { Route as ManagerReportXaRouteImport } from './routes/manager/report-xa'
import { Route as ManagerReportTruongRouteImport } from './routes/manager/report-truong'
import { Route as ManagerReportTinhRouteImport } from './routes/manager/report-tinh'
import { Route as ManagerReportBoRouteImport } from './routes/manager/report-bo'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminEngineRouteImport } from './routes/admin/engine'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as StudentLessonLessonIdRouteImport } from './routes/student/lesson.$lessonId'
import { Route as SachBaiHocLessonIdRouteImport } from './routes/sach/bai-hoc.$lessonId'
import { Route as ApiAiJsonRouteImport } from './routes/api/ai.json'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTestRoute = TeacherTestRouteImport.update({
  id: '/teacher/test',
  path: '/teacher/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProgressRoute = TeacherProgressRouteImport.update({
  id: '/teacher/progress',
  path: '/teacher/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherExamRoute = TeacherExamRouteImport.update({
  id: '/teacher/exam',
  path: '/teacher/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherBankRoute = TeacherBankRouteImport.update({
  id: '/teacher/bank',
  path: '/teacher/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignRoute = TeacherAssignRouteImport.update({
  id: '/teacher/assign',
  path: '/teacher/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAiRoute = TeacherAiRouteImport.update({
  id: '/teacher/ai',
  path: '/teacher/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/student/practice',
  path: '/student/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCompetencyRoute = StudentCompetencyRouteImport.update({
  id: '/student/competency',
  path: '/student/competency',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentBattleRoute = StudentBattleRouteImport.update({
  id: '/student/battle',
  path: '/student/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAiRoute = StudentAiRouteImport.update({
  id: '/student/ai',
  path: '/student/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAchievementsRoute = StudentAchievementsRouteImport.update({
  id: '/student/achievements',
  path: '/student/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const SachToan4Route = SachToan4RouteImport.update({
  id: '/sach/toan-4',
  path: '/sach/toan-4',
  getParentRoute: () => rootRouteImport,
} as any)
const SachKhoaHoc4Route = SachKhoaHoc4RouteImport.update({
  id: '/sach/khoa-hoc-4',
  path: '/sach/khoa-hoc-4',
  getParentRoute: () => rootRouteImport,
} as any)
const SachBookIdRoute = SachBookIdRouteImport.update({
  id: '/sach/$bookId',
  path: '/sach/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportXaRoute = ManagerReportXaRouteImport.update({
  id: '/manager/report-xa',
  path: '/manager/report-xa',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportTruongRoute = ManagerReportTruongRouteImport.update({
  id: '/manager/report-truong',
  path: '/manager/report-truong',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportTinhRoute = ManagerReportTinhRouteImport.update({
  id: '/manager/report-tinh',
  path: '/manager/report-tinh',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportBoRoute = ManagerReportBoRouteImport.update({
  id: '/manager/report-bo',
  path: '/manager/report-bo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEngineRoute = AdminEngineRouteImport.update({
  id: '/admin/engine',
  path: '/admin/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLessonLessonIdRoute = StudentLessonLessonIdRouteImport.update({
  id: '/student/lesson/$lessonId',
  path: '/student/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const SachBaiHocLessonIdRoute = SachBaiHocLessonIdRouteImport.update({
  id: '/sach/bai-hoc/$lessonId',
  path: '/sach/bai-hoc/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiJsonRoute = ApiAiJsonRouteImport.update({
  id: '/api/ai/json',
  path: '/api/ai/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/slides': typeof SlidesRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/report-bo': typeof ManagerReportBoRoute
  '/manager/report-tinh': typeof ManagerReportTinhRoute
  '/manager/report-truong': typeof ManagerReportTruongRoute
  '/manager/report-xa': typeof ManagerReportXaRoute
  '/sach/$bookId': typeof SachBookIdRoute
  '/sach/khoa-hoc-4': typeof SachKhoaHoc4Route
  '/sach/toan-4': typeof SachToan4Route
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai': typeof StudentAiRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/battle': typeof StudentBattleRoute
  '/student/competency': typeof StudentCompetencyRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai': typeof TeacherAiRoute
  '/teacher/assign': typeof TeacherAssignRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/exam': typeof TeacherExamRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/test': typeof TeacherTestRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/json': typeof ApiAiJsonRoute
  '/sach/bai-hoc/$lessonId': typeof SachBaiHocLessonIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/slides': typeof SlidesRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/report-bo': typeof ManagerReportBoRoute
  '/manager/report-tinh': typeof ManagerReportTinhRoute
  '/manager/report-truong': typeof ManagerReportTruongRoute
  '/manager/report-xa': typeof ManagerReportXaRoute
  '/sach/$bookId': typeof SachBookIdRoute
  '/sach/khoa-hoc-4': typeof SachKhoaHoc4Route
  '/sach/toan-4': typeof SachToan4Route
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai': typeof StudentAiRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/battle': typeof StudentBattleRoute
  '/student/competency': typeof StudentCompetencyRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai': typeof TeacherAiRoute
  '/teacher/assign': typeof TeacherAssignRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/exam': typeof TeacherExamRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/test': typeof TeacherTestRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/json': typeof ApiAiJsonRoute
  '/sach/bai-hoc/$lessonId': typeof SachBaiHocLessonIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/slides': typeof SlidesRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/engine': typeof AdminEngineRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/report-bo': typeof ManagerReportBoRoute
  '/manager/report-tinh': typeof ManagerReportTinhRoute
  '/manager/report-truong': typeof ManagerReportTruongRoute
  '/manager/report-xa': typeof ManagerReportXaRoute
  '/sach/$bookId': typeof SachBookIdRoute
  '/sach/khoa-hoc-4': typeof SachKhoaHoc4Route
  '/sach/toan-4': typeof SachToan4Route
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/ai': typeof StudentAiRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/battle': typeof StudentBattleRoute
  '/student/competency': typeof StudentCompetencyRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/ai': typeof TeacherAiRoute
  '/teacher/assign': typeof TeacherAssignRoute
  '/teacher/bank': typeof TeacherBankRoute
  '/teacher/exam': typeof TeacherExamRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/test': typeof TeacherTestRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/json': typeof ApiAiJsonRoute
  '/sach/bai-hoc/$lessonId': typeof SachBaiHocLessonIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gioi-thieu'
    | '/slides'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/engine'
    | '/admin/system'
    | '/admin/users'
    | '/manager/report-bo'
    | '/manager/report-tinh'
    | '/manager/report-truong'
    | '/manager/report-xa'
    | '/sach/$bookId'
    | '/sach/khoa-hoc-4'
    | '/sach/toan-4'
    | '/student/achievements'
    | '/student/ai'
    | '/student/assignments'
    | '/student/battle'
    | '/student/competency'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/ai'
    | '/teacher/assign'
    | '/teacher/bank'
    | '/teacher/exam'
    | '/teacher/progress'
    | '/teacher/reports'
    | '/teacher/test'
    | '/admin/'
    | '/manager/'
    | '/student/'
    | '/teacher/'
    | '/api/ai/chat'
    | '/api/ai/json'
    | '/sach/bai-hoc/$lessonId'
    | '/student/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gioi-thieu'
    | '/slides'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/engine'
    | '/admin/system'
    | '/admin/users'
    | '/manager/report-bo'
    | '/manager/report-tinh'
    | '/manager/report-truong'
    | '/manager/report-xa'
    | '/sach/$bookId'
    | '/sach/khoa-hoc-4'
    | '/sach/toan-4'
    | '/student/achievements'
    | '/student/ai'
    | '/student/assignments'
    | '/student/battle'
    | '/student/competency'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/ai'
    | '/teacher/assign'
    | '/teacher/bank'
    | '/teacher/exam'
    | '/teacher/progress'
    | '/teacher/reports'
    | '/teacher/test'
    | '/admin'
    | '/manager'
    | '/student'
    | '/teacher'
    | '/api/ai/chat'
    | '/api/ai/json'
    | '/sach/bai-hoc/$lessonId'
    | '/student/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/gioi-thieu'
    | '/slides'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/engine'
    | '/admin/system'
    | '/admin/users'
    | '/manager/report-bo'
    | '/manager/report-tinh'
    | '/manager/report-truong'
    | '/manager/report-xa'
    | '/sach/$bookId'
    | '/sach/khoa-hoc-4'
    | '/sach/toan-4'
    | '/student/achievements'
    | '/student/ai'
    | '/student/assignments'
    | '/student/battle'
    | '/student/competency'
    | '/student/practice'
    | '/student/profile'
    | '/teacher/ai'
    | '/teacher/assign'
    | '/teacher/bank'
    | '/teacher/exam'
    | '/teacher/progress'
    | '/teacher/reports'
    | '/teacher/test'
    | '/admin/'
    | '/manager/'
    | '/student/'
    | '/teacher/'
    | '/api/ai/chat'
    | '/api/ai/json'
    | '/sach/bai-hoc/$lessonId'
    | '/student/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GioiThieuRoute: typeof GioiThieuRoute
  SlidesRoute: typeof SlidesRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEngineRoute: typeof AdminEngineRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ManagerReportBoRoute: typeof ManagerReportBoRoute
  ManagerReportTinhRoute: typeof ManagerReportTinhRoute
  ManagerReportTruongRoute: typeof ManagerReportTruongRoute
  ManagerReportXaRoute: typeof ManagerReportXaRoute
  SachBookIdRoute: typeof SachBookIdRoute
  SachKhoaHoc4Route: typeof SachKhoaHoc4Route
  SachToan4Route: typeof SachToan4Route
  StudentAchievementsRoute: typeof StudentAchievementsRoute
  StudentAiRoute: typeof StudentAiRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentBattleRoute: typeof StudentBattleRoute
  StudentCompetencyRoute: typeof StudentCompetencyRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  TeacherAiRoute: typeof TeacherAiRoute
  TeacherAssignRoute: typeof TeacherAssignRoute
  TeacherBankRoute: typeof TeacherBankRoute
  TeacherExamRoute: typeof TeacherExamRoute
  TeacherProgressRoute: typeof TeacherProgressRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherTestRoute: typeof TeacherTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiJsonRoute: typeof ApiAiJsonRoute
  SachBaiHocLessonIdRoute: typeof SachBaiHocLessonIdRoute
  StudentLessonLessonIdRoute: typeof StudentLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/test': {
      id: '/teacher/test'
      path: '/teacher/test'
      fullPath: '/teacher/test'
      preLoaderRoute: typeof TeacherTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/progress': {
      id: '/teacher/progress'
      path: '/teacher/progress'
      fullPath: '/teacher/progress'
      preLoaderRoute: typeof TeacherProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/exam': {
      id: '/teacher/exam'
      path: '/teacher/exam'
      fullPath: '/teacher/exam'
      preLoaderRoute: typeof TeacherExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/bank': {
      id: '/teacher/bank'
      path: '/teacher/bank'
      fullPath: '/teacher/bank'
      preLoaderRoute: typeof TeacherBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assign': {
      id: '/teacher/assign'
      path: '/teacher/assign'
      fullPath: '/teacher/assign'
      preLoaderRoute: typeof TeacherAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/ai': {
      id: '/teacher/ai'
      path: '/teacher/ai'
      fullPath: '/teacher/ai'
      preLoaderRoute: typeof TeacherAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/student/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/competency': {
      id: '/student/competency'
      path: '/student/competency'
      fullPath: '/student/competency'
      preLoaderRoute: typeof StudentCompetencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/battle': {
      id: '/student/battle'
      path: '/student/battle'
      fullPath: '/student/battle'
      preLoaderRoute: typeof StudentBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/ai': {
      id: '/student/ai'
      path: '/student/ai'
      fullPath: '/student/ai'
      preLoaderRoute: typeof StudentAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/achievements': {
      id: '/student/achievements'
      path: '/student/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof StudentAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sach/toan-4': {
      id: '/sach/toan-4'
      path: '/sach/toan-4'
      fullPath: '/sach/toan-4'
      preLoaderRoute: typeof SachToan4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sach/khoa-hoc-4': {
      id: '/sach/khoa-hoc-4'
      path: '/sach/khoa-hoc-4'
      fullPath: '/sach/khoa-hoc-4'
      preLoaderRoute: typeof SachKhoaHoc4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sach/$bookId': {
      id: '/sach/$bookId'
      path: '/sach/$bookId'
      fullPath: '/sach/$bookId'
      preLoaderRoute: typeof SachBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/report-xa': {
      id: '/manager/report-xa'
      path: '/manager/report-xa'
      fullPath: '/manager/report-xa'
      preLoaderRoute: typeof ManagerReportXaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/report-truong': {
      id: '/manager/report-truong'
      path: '/manager/report-truong'
      fullPath: '/manager/report-truong'
      preLoaderRoute: typeof ManagerReportTruongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/report-tinh': {
      id: '/manager/report-tinh'
      path: '/manager/report-tinh'
      fullPath: '/manager/report-tinh'
      preLoaderRoute: typeof ManagerReportTinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/report-bo': {
      id: '/manager/report-bo'
      path: '/manager/report-bo'
      fullPath: '/manager/report-bo'
      preLoaderRoute: typeof ManagerReportBoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/engine': {
      id: '/admin/engine'
      path: '/admin/engine'
      fullPath: '/admin/engine'
      preLoaderRoute: typeof AdminEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/lesson/$lessonId': {
      id: '/student/lesson/$lessonId'
      path: '/student/lesson/$lessonId'
      fullPath: '/student/lesson/$lessonId'
      preLoaderRoute: typeof StudentLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sach/bai-hoc/$lessonId': {
      id: '/sach/bai-hoc/$lessonId'
      path: '/sach/bai-hoc/$lessonId'
      fullPath: '/sach/bai-hoc/$lessonId'
      preLoaderRoute: typeof SachBaiHocLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/json': {
      id: '/api/ai/json'
      path: '/api/ai/json'
      fullPath: '/api/ai/json'
      preLoaderRoute: typeof ApiAiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GioiThieuRoute: GioiThieuRoute,
  SlidesRoute: SlidesRoute,
  AdminAiRoute: AdminAiRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEngineRoute: AdminEngineRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  ManagerReportBoRoute: ManagerReportBoRoute,
  ManagerReportTinhRoute: ManagerReportTinhRoute,
  ManagerReportTruongRoute: ManagerReportTruongRoute,
  ManagerReportXaRoute: ManagerReportXaRoute,
  SachBookIdRoute: SachBookIdRoute,
  SachKhoaHoc4Route: SachKhoaHoc4Route,
  SachToan4Route: SachToan4Route,
  StudentAchievementsRoute: StudentAchievementsRoute,
  StudentAiRoute: StudentAiRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentBattleRoute: StudentBattleRoute,
  StudentCompetencyRoute: StudentCompetencyRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentProfileRoute: StudentProfileRoute,
  TeacherAiRoute: TeacherAiRoute,
  TeacherAssignRoute: TeacherAssignRoute,
  TeacherBankRoute: TeacherBankRoute,
  TeacherExamRoute: TeacherExamRoute,
  TeacherProgressRoute: TeacherProgressRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherTestRoute: TeacherTestRoute,
  AdminIndexRoute: AdminIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiJsonRoute: ApiAiJsonRoute,
  SachBaiHocLessonIdRoute: SachBaiHocLessonIdRoute,
  StudentLessonLessonIdRoute: StudentLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
